### ISSUE TITLE
move uc_to_assignments gist into this repo?

### ISSUE THREAD

**Issue by jairideout** [caporaso-lab/short-read-tax-assignment#45]
@gregcaporaso do we want [uc_to_assignments](https://gist.github.com/gregcaporaso/6083538) moved into this repo? That way it's one less thing for users to download, and we can better keep track of updates to it.

**Comment by nbokulich** [comment]
Closing this — This issue is way out of date, and UC is already included in ``assign_taxonomy.py``

@jairideout and @gregcaporaso : I will be clearing out old issues in this repo... so you can ignore the string of issue closures that may follow this message...
