### ISSUE TITLE
add option to compare based on subset of precomputed results

### ISSUE THREAD

**Issue by jairideout** [caporaso-lab/short-read-tax-assignment#50]
When testing out the eval framework notebooks with the usearch taxonomy assigner, I only ran usearch using the gg_13_5 database and a couple of 16S datasets. In the summarized results tables, the highest ranking classifiers are reported for datasets that I didn't run usearch against (e.g., the ITS datasets). I think it'd be helpful to have the eval framework only compare the query results to the subject results that match (e.g., databases and datasets).

There are a couple of use-cases:
- quick testing runtimes (basically what I'm doing right now)
- maybe a developer creates a novel classifier that is really good at ITS sequence classification and only wants to perform those comparisons

@gregcaporaso what do you think? This almost makes sense to be the default behavior, with a way to specify that all comparisons are performed like it is doing now.

**Comment by nbokulich** [comment]
Fixed in PR #125 . Now supported with `append` parameter.
