### ISSUE TITLE
finalize simulated community notebooks

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/short-read-tax-assignment#91]
- [x] write index 
- [x] update command generation to be command execution
- [x] merge biom prep notebook with command execution notebook
- [x] define base analysis notebook(s)
- [x] create taxa level notebooks
- [ ] add final analysis results as they're ready

**Comment by nbokulich** [comment]
These no longer exist in their ancient form. The new evolution of simulated cross-validated read classification notebooks are complete.
