### ISSUE TITLE
create script to translate a uc file into taxonomy assignments...

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/short-read-tax-assignment#94]
this will let us easily apply the uclust consensus assignment approach to vsearch output

**Comment by nbokulich** [comment]
This has long since been implemented.

Though @gregcaporaso this brings up an interesting question — perhaps the vsearch taxonomy classifier that you created last winter should be added as a feature of the vsearch plugin? Let me know if you want me to create an issue on the repo for that plugin.
